name: Deploymnet Workflow
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy changes to server via ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ducksnutsfishing.com
        username: andrewb
        key: ${{ secrets.DNF_SECRET }}
        port: 22
        script: |
          cd blog
          git pull origin master
          _build/prod/rel/blog/bin/blog stop
          rm -rf _build
          mix deps.get --only prod
          MIX_ENV=prod mix compile --force
          npm run deploy --prefix ./assets
          mix phx.digest
          MIX_ENV=prod NODE_NAME=blog_prod mix release prod --overwrite
          _build/prod/rel/blog/bin/blog daemon
